// Указываем зависимости для скрипта сборки
buildscript {
    repositories {
        google() // Репозиторий Google для Android-плагинов
        mavenCentral() // Центральный репозиторий Maven
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1' // Версия плагина Gradle для Android (8.9.0 не существует)
    }
}

// Применяем плагины
plugins {
    id 'com.android.application' version '8.1.1' apply false // Плагин для Android-приложения
    id 'com.android.library' version '8.1.1' apply false // Плагин для Android-библиотеки
    id 'maven-publish' // Плагин для публикации в Maven
}

// Настройка публикации после оценки проекта
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                // Используем компонент "release" из androidComponents
                from components.find { it.name == "release" } // Нахождение компонента по имени "release"
                groupId = 'com.example' // Группа артефакта
                artifactId = 'your-library' // Имя артефакта
                version = '1.0.0' // Версия артефакта
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/Jackasm/AuditoriumControlApp")
                credentials {
                    username = System.getenv("GITHUB_ACTOR") // Имя пользователя GitHub
                    password = System.getenv("GITHUB_TOKEN") // Токен GitHub
                }
            }
        }
    }
}

// Задача очистки
task clean(type: Delete) {
    delete rootProject.buildDir // Очистка директории сборки
}
