buildscript {

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.0' // Версия плагина Gradle для Android


    }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java  // Публикует Java-компонент
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Jackasm/AuditoriumControlApp")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
plugins {
    id 'com.android.application' version '8.9.0' apply false
    id 'com.android.library' version '8.9.0' apply false
    id 'maven-publish'
}


task clean(type: Delete) {
    delete rootProject.buildDir
}










