name: Build and Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
    
    - name: Rename APK
      run: |
        cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/AuditoriumControl.apk
    
    - name: Cleanup old releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 1  # Оставляем только последний релиз
        delete_tags: true  # Удаляем и теги
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: AuditoriumControl Build ${{ github.run_number }}
        files: app/build/outputs/apk/debug/AuditoriumControl.apk
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    - name: Create Release
      uses: softprops/action-gh-release@v1  # <-- ДРУГОЙ ЭКШН
      with:
        tag_name: build-${{ github.run_number }}
        name: AuditoriumControl Build ${{ github.run_number }}
        files: app/build/outputs/apk/debug/AuditoriumControl.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
